VERSION             "1"
CONFIG              "C:\trees\cod2\bin\StringEd.cfg"
FILENOTES           ""

REFERENCE           HINT_CYCLE_WEAPONS
LANG_ENGLISH        "Press [{weapnext}] to cycle through weapons."

REFERENCE           HINT_TOGGLE_THERMAL
LANG_ENGLISH        "Press [{+usereload}] to toggle thermal vision between white hot and black hot."

REFERENCE           HINT_ZOOM_AND_FIRE
LANG_ENGLISH        "Pull [{+speed}] to control zoom and  pull [{+attack}] to fire."

REFERENCE           DO_NOT_ENGAGE
LANG_ENGLISH        "You have not been cleared to fire. Mission failed."

REFERENCE           CHURCH_DAMAGED
LANG_ENGLISH        "You damaged the church. Mission failed."

REFERENCE           ESCAPEVEHICLE_DESTROYED
LANG_ENGLISH        "The friendly escape convoy was destroyed. Mission failed."

REFERENCE           HUD_TOP_BAR
LANG_ENGLISH        "0         A-G        MAN    NARO"

REFERENCE           HUD_LEFT_BLOCK
LANG_ENGLISH        "RAY\nFF 30\nLIR\n\nBORE"

REFERENCE           HUD_RIGHT_BLOCK
LANG_ENGLISH        "N\nT\n\nS\nF\n\nQ\nZ\n\nT\nG\nT"

REFERENCE           HUD_BOTTOM_BLOCK
LANG_ENGLISH        "L1514    RDY"

REFERENCE           HUD_THERMAL_WHOT
LANG_ENGLISH        "WHOT"

REFERENCE           HUD_THERMAL_BHOT
LANG_ENGLISH        "BHOT"

REFERENCE           HUD_WEAPON_105MM
LANG_ENGLISH        "105 mm"

REFERENCE           HUD_WEAPON_40MM
LANG_ENGLISH        "40 mm"

REFERENCE           HUD_WEAPON_25MM
LANG_ENGLISH        "25 mm"

REFERENCE           HUD_AGL
LANG_ENGLISH        "&&1 AGL"

ENDMARKER


