VERSION             "1"
CONFIG              "C:\trees\cod2\bin\StringEd.cfg"
FILENOTES           ""

REFERENCE           OBJ_DOCKS1
LANG_ENGLISH        "Eliminate the Axis naval artillery crews at the docks. [&&1 remaining]"

REFERENCE           TITLE
LANG_ENGLISH        "Intervention"

REFERENCE           PLACE
LANG_ENGLISH        "Black Sea, 40 knots South of Ukranian Border"

REFERENCE           DATE
LANG_ENGLISH        "Day 4 - 0100 hr"

REFERENCE           INFO
LANG_ENGLISH        "British SAS intercepting a cargo freighter"


ENDMARKER


