VERSION             "1"
CONFIG              "C:\trees\cod2\bin\StringEd.cfg"
FILENOTES           ""

REFERENCE           OBJ_DOCKS1
LANG_ENGLISH        "Eliminate the Axis naval artillery crews at the docks. [&&1 remaining]"

REFERENCE           OBJ_ALASSAD
LANG_ENGLISH        "Photograph and identify the remains of Al-Assad."

REFERENCE           OBJ_PHOTO_BACKHALL
LANG_ENGLISH        "Photograph the officer's face on the desk."

REFERENCE           OBJ_PHOTO_BATHROOM
LANG_ENGLISH        "Photograph the officer's face in the bathroom."

REFERENCE           OBJ_PHOTO_DROPDOWN
LANG_ENGLISH        "Photograph the officer's face under the rubble."

REFERENCE           OBJ_PHOTO_FINAL
LANG_ENGLISH        "Photograph the officer's face by the rubble."

REFERENCE           OBJ_PHOTO_PRISON
LANG_ENGLISH        "Photograph the officer's face by the jail cell."

REFERENCE           OBJ_PHOTO_STAIRS
LANG_ENGLISH        "Photograph the officer's face by the broken wall."

REFERENCE           OBJ_DETPACK
LANG_ENGLISH        "Plant a detpack on the compromised wall."

REFERENCE           OBJ_SECURE
LANG_ENGLISH        "Secure the Landing Zone."

REFERENCE           HINTSTR_CAMERA_CLICK
LANG_ENGLISH        "  Pull [{+usereload}] to zoom in.\nPull [{+attack}] to take a picture."

REFERENCE           HINTSTR_CAMERA_OUT
LANG_ENGLISH        "Press [{+usereload}] to pull out your camera."

REFERENCE           HINTSTR_DETPACK
LANG_ENGLISH        "Hold &&1 to plant the detpack."

REFERENCE           HINTSTR_FASTROPE
LANG_ENGLISH        "Jump towards the cable to fast rope down."

REFERENCE           TITLE
LANG_ENGLISH        "Descent"

REFERENCE           PLACE
LANG_ENGLISH        "Riyadh, capital of Saudi Arabia"

REFERENCE           DATE
LANG_ENGLISH        "Day 6 - 1310 hr"

REFERENCE           INFO
LANG_ENGLISH        "U.S. Marines entering underground command bunker"


ENDMARKER


